spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_springboot
    username: learn_user
    password: learn_password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update    # dev: update ; prod: validate or none + migrations
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# logging:
#   level:
#     root: INFO
